apiVersion: v1
kind: Namespace
metadata:
  name: c2c-sk-java-gradle-pg-ns
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: c2c-sk-java-gradle-pg-deployment
  namespace: c2c-sk-java-gradle-pg-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 792373136340.dkr.ecr.us-east-2.amazonaws.com/c2c:a28a556d16611a8e1ce712304e63049e0b0effd9

---
#Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: c2c-sk-java-gradle-pg-label
  name: c2c-sk-java-gradle-pg-service
  namespace: c2c-sk-java-gradle-pg-ns
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  sessionAffinity: None
  type: LoadBalancer

---